# Generated by Django 2.0.3 on 2018-10-10 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('size', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('buy', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_dish', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('size', models.BooleanField(default=False)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_dish', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salad_dish', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('size', models.BooleanField(default=False)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicilian_dish', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('size', models.BooleanField(default=False)),
                ('Xcheese', models.BooleanField(default=False)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs0_dish', to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateDinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplatePasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateRegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1SmallPrice', models.FloatField(blank=True, default=None)),
                ('Topping2SmallPrice', models.FloatField(blank=True, default=None)),
                ('Topping3SmallPrice', models.FloatField(blank=True, default=None)),
                ('Topping1LargePrice', models.FloatField(blank=True, default=None)),
                ('Topping2LargePrice', models.FloatField(blank=True, default=None)),
                ('Topping3LargePrice', models.FloatField(blank=True, default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateSalad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateSicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1SmallPrice', models.FloatField(blank=True, default=None)),
                ('Topping2SmallPrice', models.FloatField(blank=True, default=None)),
                ('Topping3SmallPrice', models.FloatField(blank=True, default=None)),
                ('Topping1LargePrice', models.FloatField(blank=True, default=None)),
                ('Topping2LargePrice', models.FloatField(blank=True, default=None)),
                ('Topping3LargePrice', models.FloatField(blank=True, default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('XCheesePrice', models.FloatField(blank=True, default=0.5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='sub',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='orders.TemplateSub'),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='orders.TemplateSicilianPizza'),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='sic_dish', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='salad',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='orders.TemplateSalad'),
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='orders.TemplateRegularPizza'),
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='reg_dish', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pasta',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='orders.TemplatePasta'),
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='din_dish', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='orders.TemplateDinnerPlatter'),
        ),
    ]
