# Generated by Django 2.0.3 on 2018-09-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCheese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NonSizableDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('SmallPrice', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MyOrder', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SmallSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('big', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SizableDish',
            fields=[
                ('nonsizabledish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NonSizableDish')),
                ('LargePrice', models.FloatField(blank=True, default=None, null=True)),
            ],
            bases=('orders.nonsizabledish',),
        ),
        migrations.CreateModel(
            name='TemplatePasta',
            fields=[
                ('nonsizabledish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NonSizableDish')),
            ],
            bases=('orders.nonsizabledish',),
        ),
        migrations.CreateModel(
            name='TemplateSalad',
            fields=[
                ('nonsizabledish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.NonSizableDish')),
            ],
            bases=('orders.nonsizabledish',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('templatepasta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.TemplatePasta')),
                ('orders', models.ManyToManyField(blank=True, related_name='pasta_dish', to='orders.Order')),
            ],
            bases=('orders.templatepasta',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('templatesalad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.TemplateSalad')),
                ('orders', models.ManyToManyField(blank=True, related_name='salad_dish', to='orders.Order')),
            ],
            bases=('orders.templatesalad',),
        ),
        migrations.CreateModel(
            name='TemplateDinnerPlatter',
            fields=[
                ('sizabledish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.SizableDish')),
            ],
            bases=('orders.sizabledish',),
        ),
        migrations.CreateModel(
            name='TemplateRegularPizza',
            fields=[
                ('sizabledish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.SizableDish')),
                ('Topping1SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3LargePrice', models.FloatField(blank=True, default=None, null=True)),
            ],
            bases=('orders.sizabledish',),
        ),
        migrations.CreateModel(
            name='TemplateSicilianPizza',
            fields=[
                ('sizabledish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.SizableDish')),
                ('Topping1SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3SmallPrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping1LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping2LargePrice', models.FloatField(blank=True, default=None, null=True)),
                ('Topping3LargePrice', models.FloatField(blank=True, default=None, null=True)),
            ],
            bases=('orders.sizabledish',),
        ),
        migrations.CreateModel(
            name='TemplateSub',
            fields=[
                ('sizabledish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.SizableDish')),
                ('XCheesePrice', models.FloatField(blank=True, default=0.5, null=True)),
            ],
            bases=('orders.sizabledish',),
        ),
        migrations.AddField(
            model_name='sizabledish',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='dish', to='orders.SmallSize'),
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('templatedinnerplatter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.TemplateDinnerPlatter')),
                ('orders', models.ManyToManyField(blank=True, related_name='din_dish', to='orders.Order')),
            ],
            bases=('orders.templatedinnerplatter',),
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('templateregularpizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.TemplateRegularPizza')),
                ('no_of_toppings', models.IntegerField(default=0)),
                ('orders', models.ManyToManyField(blank=True, related_name='regular_dish', to='orders.Order')),
                ('toppings', models.ManyToManyField(blank=True, related_name='reg_dish', to='orders.Topping')),
            ],
            bases=('orders.templateregularpizza',),
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('templatesicilianpizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.TemplateSicilianPizza')),
                ('no_of_toppings', models.IntegerField(default=0)),
                ('orders', models.ManyToManyField(blank=True, related_name='sicilian_dish', to='orders.Order')),
                ('toppings', models.ManyToManyField(blank=True, related_name='sic_dish', to='orders.Topping')),
            ],
            bases=('orders.templatesicilianpizza',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('templatesub_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.TemplateSub')),
                ('Xcheese', models.ManyToManyField(related_name='subs_dish', to='orders.ExtraCheese')),
                ('orders', models.ManyToManyField(blank=True, related_name='subs0_dish', to='orders.Order')),
            ],
            bases=('orders.templatesub',),
        ),
    ]
