# Generated by Django 2.0.3 on 2018-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizabledish',
            name='size',
        ),
        migrations.AddField(
            model_name='sizabledish',
            name='size',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='sub',
            name='Xcheese',
        ),
        migrations.AddField(
            model_name='sub',
            name='Xcheese',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ExtraCheese',
        ),
        migrations.DeleteModel(
            name='SmallSize',
        ),
    ]
