# Generated by Django 2.0.3 on 2018-09-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_confirmed_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmed_order',
            name='order',
        ),
        migrations.DeleteModel(
            name='Confirmed_Order',
        ),
    ]
