# Generated by Django 2.0.3 on 2018-10-11 16:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181011_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='LargePrice',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='SmallPrice',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='LargePrice',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='SmallPrice',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='LargePrice',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='SmallPrice',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='LargePrice',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='SmallPrice',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='LargePrice',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='SmallPrice',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='LargePrice',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='SmallPrice',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='name',
        ),
        migrations.AddField(
            model_name='regularpizza',
            name='no_of_toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='no_of_toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='templatedinnerplatter',
            name='LargePrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='templateregularpizza',
            name='LargePrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='templatesicilianpizza',
            name='LargePrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='templatesub',
            name='LargePrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
    ]
