# Generated by Django 2.0.3 on 2018-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181011_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='string',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='string',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
