# Generated by Django 2.0.3 on 2018-10-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181011_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='string',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='string',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
