# Generated by Django 2.0.3 on 2018-10-23 08:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181011_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatesub',
            name='XCheesePrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=7),
        ),
    ]
