# Generated by Django 2.0.3 on 2018-10-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20181023_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Steak_Cheese',
            fields=[
                ('sub_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Sub')),
                ('no_of_add_ons', models.IntegerField(default=0)),
                ('string', models.CharField(blank=True, max_length=64, null=True)),
                ('Add_ons', models.ManyToManyField(blank=True, related_name='Steak_Cheese', to='orders.Add_on')),
            ],
            bases=('orders.sub',),
        ),
    ]
