# Generated by Django 2.0.3 on 2018-10-24 09:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_on_steak_cheese'),
    ]

    operations = [
        migrations.AddField(
            model_name='steak_cheese',
            name='add_on_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=7),
        ),
    ]
