# Generated by Django 2.0.3 on 2018-10-24 09:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_steak_cheese_add_on_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steak_cheese',
            name='add_on_cost',
        ),
        migrations.AddField(
            model_name='templatesub',
            name='add_on_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.5'), max_digits=7),
        ),
    ]
