# Generated by Django 2.0.3 on 2018-10-24 09:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20181024_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesub',
            name='add_on_cost',
        ),
        migrations.AddField(
            model_name='add_on',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=7),
        ),
    ]
